# =============================================================================
# WRITTEN BY STUDENT — change these values to control the dataset
# =============================================================================
import csv
import random


# Unsafe limits for 8 hours of exposure (from experiment brief)
# CO    : 10   mg/m3
# NOx   : 2500 ppb
# PM2.5 : 5    mg/m3
# O3    : 60   ug/m3
# SO2   : 5.2  mg/m3

LIMITS = {
    'CO_mg_m3':    10.0,
    'NOx_ppb':   2500.0,
    'PM25_mg_m3':   5.0,
    'O3_ug_m3':    60.0,
    'SO2_mg_m3':   5.2
}

# Additive formula (from experiment brief):
#   CO/10 + NOx/2500 + PM2.5/5 + O3/60 + SO2/5.2
#   if sum > 1 → unsafe (1)
#   if sum ≤ 1 → safe   (0)


def additive_score(co, nox, pm25, o3, so2):
    return (co / LIMITS['CO_mg_m3'] +
            nox / LIMITS['NOx_ppb'] +
            pm25 / LIMITS['PM25_mg_m3'] +
            o3 / LIMITS['O3_ug_m3'] +
            so2 / LIMITS['SO2_mg_m3'])


def label(score):
    return 1 if score > 1.0 else 0


NUM_ROWS = 20000    # how many rows to generate
OUTPUT_FILE = 'air_quality_dataset.csv'


# randomise seed for different data each time
random.seed(random.randint(0, 1000000))
rows = []

# =============================================================================
# WRITTEN BY AI
# =============================================================================

for i in range(NUM_ROWS):
    # What this script does is generate a sdataset with aternating rows of safe and unsafe air data.
    # These Values are generated by creating random numbers inbetween 0-1 for safe and 1< for unsafe values.
    # Then  the random numbers are multiplied by the limits to get a realistic data set. The data is then saved to a csv file.
    if i % 2 == 0:
        # SAFE row: generate 5 fractions that add up to less than 1
        budget = random.uniform(0.1, 0.99)
        cuts = sorted([random.random() for _ in range(4)])
        fracs = [cuts[0],
                 cuts[1] - cuts[0],
                 cuts[2] - cuts[1],
                 cuts[3] - cuts[2],
                 1 - cuts[3]]
        fracs = [f * budget for f in fracs]
    else:
        # UNSAFE row: generate 5 fractions that add up to more than 1
        budget = random.uniform(1.01, 2.0)
        cuts = sorted([random.random() for _ in range(4)])
        fracs = [cuts[0],
                 cuts[1] - cuts[0],
                 cuts[2] - cuts[1],
                 cuts[3] - cuts[2],
                 1 - cuts[3]]
        fracs = [min(f * budget, 1.2) for f in fracs]  # cap at 120% of limit

    co = round(fracs[0] * LIMITS['CO_mg_m3'],   3)
    nox = round(fracs[1] * LIMITS['NOx_ppb'],    2)
    pm25 = round(fracs[2] * LIMITS['PM25_mg_m3'], 3)
    o3 = round(fracs[3] * LIMITS['O3_ug_m3'],   2)
    so2 = round(fracs[4] * LIMITS['SO2_mg_m3'], 2)

    score = additive_score(co, nox, pm25, o3, so2)
    rows.append([co, nox, pm25, o3, so2, label(score)])

with open(OUTPUT_FILE, 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(
        ['CO_mg_m3', 'NOx_ppb', 'PM25_mg_m3', 'O3_ug_m3', 'SO2_mg_m3', 'quality'])
    writer.writerows(rows)

safe_count = sum(1 for r in rows if r[5] == 0)
unsafe_count = sum(1 for r in rows if r[5] == 1)

print(f"Generated {NUM_ROWS} rows → {OUTPUT_FILE}")
print(f"  Safe   (0): {safe_count}  ({safe_count / NUM_ROWS * 100:.1f}%)")
print(f"  Unsafe (1): {unsafe_count}  ({unsafe_count / NUM_ROWS * 100:.1f}%)")


# =============================================================================
# END AI CODE
# =============================================================================
